/*
  Warnings:

  - The values [ADVANCEDPAWN,ARABIANMATE,ATTACKINGF2F7,BACKRANKMATE,BISHOPENDGAME,BODENMATE,CAPTURINGDEFENDER,CORNERMATE,DEFENSIVEMOVE,DISCOVEREDATTACK,DOUBLEBISHOPMATE,DOUBLECHECK,ENPASSANT,EXPOSEDKING,HANGINGPIECE,HOOKMATE,KINGSIDEATTACK,KNIGHTENDGAME,MASTERVSMASTER,MATEIN1,MATEIN2,MATEIN3,MATEIN4,ONEMOVE,PAWNENDGAME,QUEENENDGAME,QUEENROOKENDGAME,QUEENSIDEATTACK,QUIETMOVE,ROOKENDGAME,SMOTHEREDMATE,SUPERGM,TRAPPEDPIECE,VERYLONG,VUKOVICMATE,XRAYATTACK] on the enum `PuzzleTheme` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "PuzzleTheme_new" AS ENUM ('ADVANCED_PAWN', 'ADVANTAGE', 'ARABIAN_MATE', 'ATTACKING_F2_F7', 'ATTRACTION', 'BACK_RANK_MATE', 'BISHOP_ENDGAME', 'BODEN_MATE', 'CAPTURING_DEFENDER', 'CLEARANCE', 'CORNER_MATE', 'CRUSHING', 'DEFENSIVE_MOVE', 'DEFLECTION', 'DISCOVERED_ATTACK', 'DOUBLE_BISHOP_MATE', 'DOUBLE_CHECK', 'ENDGAME', 'EN_PASSANT', 'EQUALITY', 'EXPOSED_KING', 'FORK', 'HANGING_PIECE', 'HOOK_MATE', 'INTERFERENCE', 'INTERMEZZO', 'KINGSIDE_ATTACK', 'KNIGHT_ENDGAME', 'LONG', 'MASTER', 'MASTER_VS_MASTER', 'MATE', 'MATE_IN1', 'MATE_IN2', 'MATE_IN3', 'MATE_IN4', 'MIDDLEGAME', 'ONE_MOVE', 'OPENING', 'PAWN_ENDGAME', 'PIN', 'PROMOTION', 'QUEENSIDE_ATTACK', 'QUEEN_ENDGAME', 'QUEEN_ROOK_ENDGAME', 'QUIET_MOVE', 'ROOK_ENDGAME', 'SACRIFICE', 'SHORT', 'SKEWER', 'SMOTHERED_MATE', 'SUPER_G_M', 'TRAPPED_PIECE', 'VERY_LONG', 'VUKOVIC_MATE', 'X_RAY_ATTACK', 'ZUGZWANG');
ALTER TABLE "public"."Puzzle" ALTER COLUMN "themes" DROP DEFAULT;
ALTER TABLE "Puzzle" ALTER COLUMN "themes" TYPE "PuzzleTheme_new"[] USING ("themes"::text::"PuzzleTheme_new"[]);
ALTER TYPE "PuzzleTheme" RENAME TO "PuzzleTheme_old";
ALTER TYPE "PuzzleTheme_new" RENAME TO "PuzzleTheme";
DROP TYPE "public"."PuzzleTheme_old";
ALTER TABLE "Puzzle" ALTER COLUMN "themes" SET DEFAULT ARRAY[]::"PuzzleTheme"[];
COMMIT;
